#pragma once

#if 1

enum 
{
    MF_LV_KEY_QUIT_SHORT_PRESS = 100,
    MF_LV_KEY_QUIT_LONG_PRESS,
    MF_LV_KEY_QUIT_DOUBLE_PRESS,
    MF_LV_KEY_QUIT_TRIPLE_PRESS,

    MF_LV_KEY_OK_SHORT_PRESS,
    MF_LV_KEY_OK_LONG_PRESS,
    MF_LV_KEY_OK_DOUBLE_PRESS,
    MF_LV_KEY_OK_TRIPLE_PRESS,

    MF_LV_KEY_UP_SHORT_PRESS,
    MF_LV_KEY_UP_LONG_PRESS,
    MF_LV_KEY_UP_DOUBLE_PRESS,
    MF_LV_KEY_UP_TRIPLE_PRESS,

    MF_LV_KEY_DOWN_SHORT_PRESS,
    MF_LV_KEY_DOWN_LONG_PRESS,
    MF_LV_KEY_DOWN_DOUBLE_PRESS,
    MF_LV_KEY_DOWN_TRIPLE_PRESS,

    MF_LV_KEY_F1_SHORT_PRESS,
    MF_LV_KEY_F1_LONG_PRESS,
    MF_LV_KEY_F1_DOUBLE_PRESS,
    MF_LV_KEY_F1_TRIPLE_PRESS,

    MF_LV_KEY_F2_SHORT_PRESS,
    MF_LV_KEY_F2_LONG_PRESS,
    MF_LV_KEY_F2_DOUBLE_PRESS,
    MF_LV_KEY_F2_TRIPLE_PRESS,

    MF_LV_KEY_ADD_SHORT_PRESS,
    MF_LV_KEY_ADD_LONG_PRESS,
    MF_LV_KEY_ADD_DOUBLE_PRESS,
    MF_LV_KEY_ADD_TRIPLE_PRESS,

    MF_LV_KEY_FUNC_SHORT_PRESS,
    MF_LV_KEY_FUNC_LONG_PRESS,
    MF_LV_KEY_FUNC_DOUBLE_PRESS,
    MF_LV_KEY_FUNC_TRIPLE_PRESS,

    MF_LV_KEY_CANCEL_SHORT_PRESS,
    MF_LV_KEY_CANCEL_LONG_PRESS,
    MF_LV_KEY_CANCEL_DOUBLE_PRESS,
    MF_LV_KEY_CANCEL_TRIPLE_PRESS,

    MF_LV_KEY_BACKSPACE_SHORT_PRESS,
    MF_LV_KEY_BACKSPACE_LONG_PRESS,
    MF_LV_KEY_BACKSPACE_DOUBLE_PRESS,
    MF_LV_KEY_BACKSPACE_TRIPLE_PRESS,//139

  

    MF_LV_KEY_1_SHORT_PRESS,
    MF_LV_KEY_1_LONG_PRESS,
    MF_LV_KEY_1_DOUBLE_PRESS,
    MF_LV_KEY_1_TRIPLE_PRESS,

    MF_LV_KEY_2_SHORT_PRESS,
    MF_LV_KEY_2_LONG_PRESS,
    MF_LV_KEY_2_DOUBLE_PRESS,
    MF_LV_KEY_2_TRIPLE_PRESS,

    MF_LV_KEY_3_SHORT_PRESS,
    MF_LV_KEY_3_LONG_PRESS,
    MF_LV_KEY_3_DOUBLE_PRESS,
    MF_LV_KEY_3_TRIPLE_PRESS,

    MF_LV_KEY_4_SHORT_PRESS,
    MF_LV_KEY_4_LONG_PRESS,
    MF_LV_KEY_4_DOUBLE_PRESS,
    MF_LV_KEY_4_TRIPLE_PRESS,

    MF_LV_KEY_5_SHORT_PRESS,
    MF_LV_KEY_5_LONG_PRESS,
    MF_LV_KEY_5_DOUBLE_PRESS,
    MF_LV_KEY_5_TRIPLE_PRESS,

    MF_LV_KEY_6_SHORT_PRESS,
    MF_LV_KEY_6_LONG_PRESS,
    MF_LV_KEY_6_DOUBLE_PRESS,
    MF_LV_KEY_6_TRIPLE_PRESS,

    MF_LV_KEY_7_SHORT_PRESS,
    MF_LV_KEY_7_LONG_PRESS,
    MF_LV_KEY_7_DOUBLE_PRESS,
    MF_LV_KEY_7_TRIPLE_PRESS,

    MF_LV_KEY_8_SHORT_PRESS,
    MF_LV_KEY_8_LONG_PRESS,
    MF_LV_KEY_8_DOUBLE_PRESS,
    MF_LV_KEY_8_TRIPLE_PRESS,

    MF_LV_KEY_9_SHORT_PRESS,
    MF_LV_KEY_9_LONG_PRESS,
    MF_LV_KEY_9_DOUBLE_PRESS,
    MF_LV_KEY_9_TRIPLE_PRESS,

    MF_LV_KEY_0_SHORT_PRESS,
    MF_LV_KEY_0_LONG_PRESS,
    MF_LV_KEY_0_DOUBLE_PRESS,
    MF_LV_KEY_0_TRIPLE_PRESS,

   

       
};


#endif
