#pragma once
//#ifndef CPU_EC600U | WIN32 //Remove invalid definitions CHAR 2023.11.13 15:35
#if !defined(CPU_EC600U)
enum{
	_START_PRIO = 0,
	_SYS_TIMER_TASK_PRIO,
	_AU_TASK_PRIO,
	_ATCINIT_TASK_PRIO,
	_WU_TASK_PRIO,
	_WIFIINIT_TASK_PRIO,				// 5
	_MODEM_RECV_TASK_PRIO ,
	_MODEM_PROC_TASK_PRIO ,
	_DEV_PROC_TASK_PRIO ,
	_TASK_TTS_TASK_PRIO,

	_RPC_TASK_PRIO,						// 10
	_BLOOTHI4_TASK_PRIO,
	_TASK_TEST_TASK_PRIO,
	_TASK_REFRESH_TASK_PRIO,
	_TASK_DRIVER_TASK_PRIO,
	_TMS_TASK_PRIO,						
#if OS_EC100Y  | CPU_EC600U
	_TASK_TTS_TASK_PALY_PRIO,
#endif 
	_TASK_NET_TASK_PRIO,
	_APP_TASK_MIN_PRIO = 20,
	_APP_TASK_MAX_PRIO = 22,
	_STK_CHK_TASK_PRIO = 29,
	_TASK_KEY_TASK_PRIO,
};
#else

enum{
	_START_PRIO = 4,
	_SYS_TIMER_TASK_PRIO,
	_AU_TASK_PRIO,
	_ATCINIT_TASK_PRIO,
	_WU_TASK_PRIO,
	_WIFIINIT_TASK_PRIO,				// 5
	_MODEM_RECV_TASK_PRIO ,
	_MODEM_PROC_TASK_PRIO ,
	_DEV_PROC_TASK_PRIO ,
	_TASK_TTS_TASK_PRIO,

	_RPC_TASK_PRIO,						// 10
	_BLOOTHI4_TASK_PRIO,
	_TASK_TEST_TASK_PRIO,
	_TASK_REFRESH_TASK_PRIO,
	_TASK_DRIVER_TASK_PRIO,
	_TMS_TASK_PRIO,						


	_TASK_TTS_TASK_PALY_PRIO,
	_TASK_NET_TASK_PRIO,
	_APP_TASK_MIN_PRIO,
	_APP_TASK_MAX_PRIO,
	_TASK_KEY_TASK_PRIO,
	_STK_CHK_TASK_PRIO,
};
#endif 

#define _MODEM_RECV_TASK_SIZE	512
#define _MODEM_PROC_TASK_SIZE	512


#ifdef OS_M56

#define _ATCINIT_TASK_SIZE		64  
#define _AU_TASK_SIZE			64

#define _WIFIINIT_TASK_SIZE		64
#define _WU_TASK_SIZE			64
#else
#define _ATCINIT_TASK_SIZE		512  
#define _AU_TASK_SIZE			512

#define _WIFIINIT_TASK_SIZE		512
#define _WU_TASK_SIZE			512

#endif


#define _BLOOTHI4_TASK_SIZE		512
#define _BLOOTHI4_TASK_SIZE			512

#define _TIMER_TASK_SIZE		512
#define _TMS_TASK_SIZE			1024
#define _STK_CHK_TASK_SIZE		128
#define _TASK_TEST_TASK_SZIE	256
#define _TTS_TASK_SIZE			(512*10)


